name: Rust

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Test Release
        run: cargo test --release
      - name: Test
        run: cargo test
      - name: Test (Example) Release
        working-directory: ./example/i18n
        run: cargo test --release
      - name: Test (Example)
        working-directory: ./example/i18n
        run: cargo test
